# **DM Python pour la Datascience**

### Import des données

In [21]:
import pandas as pd
from great_tables import GT, style, loc,md

In [7]:
df = pd.read_csv(
'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)
df.head()

/var/folders/8v/sm2jq2dn629g8g885ws0nmnc0000gn/T/ipykernel_77091/518893530.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

## 1. Explorations générales
### Question 1

In [ ]:
df['code_commune'] = df['code_departement'].astype(str) + df['code_commune'].astype(str).str.zfill(3)
df.head()

df['candidat'] = df['prenom'] + ' ' + df['nom']
df.tail()

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
528670,fr_etranger,Français établis hors de France,fr_etranger229,Zurich,NaN,nuls,31,NaN
528671,fr_etranger,Français établis hors de France,fr_etranger231,Taipei,NaN,nuls,2,NaN
528672,fr_etranger,Français établis hors de France,fr_etranger233,Nour-Soultan,NaN,nuls,0,NaN
528673,fr_etranger,Français établis hors de France,fr_etranger234,Monterrey,NaN,nuls,2,NaN
528674,fr_etranger,Français établis hors de France,fr_etranger235,Bahamas (Nassau),NaN,nuls,0,NaN

### Question 2

In [9]:
nombre_candidats = df['candidat'].nunique()
print(f"En 2022, il y avait {nombre_candidats} candidats à l’élection présidentielle.")

En 2022, il y avait 12 candidats à l’élection présidentielle.

### Question 3

In [ ]:
# Calculer les scores nationaux de chaque candidat. Représenter dans ce tableau, pour chaque
# candidat, le nombre de voix et le pourcatage des votes exprimés (c’est􀀷à􀀷dire en retirant abstentions
# et votes non exprimés).
# Représenter cela dans un dataframe ou, pour avoir tous les points, dans un tableau mis en forme
# via great_tables (il n’est pas obligatoire d’aller aussi loin dans la mise en forme mais essayez
# d’obtenir un beau tableau tout de même).
scores_nationaux = df.groupby('candidat')['voix'].sum().reset_index()
scores_nationaux['pourcentage'] = (scores_nationaux['voix'] / scores_nationaux['voix'].sum()) * 100
scores_nationaux = scores_nationaux.sort_values(by='voix', ascending=False)
scores_nationaux.head()

              candidat     voix  pourcentage
1      Emmanuel MACRON  9783058    27.845822
5        Marine LE PEN  8133828    23.151568
4   Jean-Luc MÉLENCHON  7712520    21.952386
11        Éric ZEMMOUR  2485226     7.073776
9     Valérie PÉCRESSE  1679001     4.778993

In [ ]:
scores_nationaux = df.groupby('candidat')['voix'].sum().reset_index()
scores_nationaux['pourcentage'] = (scores_nationaux['voix'] / scores_nationaux['voix'].sum()) * 100
scores_nationaux = scores_nationaux.sort_values(by='voix', ascending=False).reset_index(drop=True)


scores_nationaux.insert(0, 'rang', range(1, len(scores_nationaux) + 1))

scores_nationaux['voix_fmt'] = scores_nationaux['voix'].apply(lambda x: f"{x:,.0f}".replace(",", " "))
scores_nationaux['pct_fmt'] = scores_nationaux['pourcentage'].apply(lambda x: f"{x:.2f} %")

# Tableau Great_tables
(
    GT(scores_nationaux[["candidat", "voix_fmt", "pct_fmt"]])
    .tab_header(title=md("**Election**"), subtitle="Résultats du premier tour (📅 10 avril 2022)")
    .tab_style(style=style.text(font="Times New Roman"), locations=loc.body())
    .tab_style(style=style.text(font="Times New Roman"), locations=loc.column_labels())
    .tab_style(style=style.text(font="Times New Roman"), locations=loc.title())
    .tab_style(style=style.text(font="Times New Roman"), locations=loc.subtitle())
    .cols_label(candidat="Candidat", voix_fmt="Nombre votes (total)", pct_fmt="Score (% votes exprimés)")
)

GT(_tbl_data=                 candidat   voix_fmt  pct_fmt
0         Emmanuel MACRON  9 783 058  27.85 %
1           Marine LE PEN  8 133 828  23.15 %
2      Jean-Luc MÉLENCHON  7 712 520  21.95 %
3            Éric ZEMMOUR  2 485 226   7.07 %
4        Valérie PÉCRESSE  1 679 001   4.78 %
5           Yannick JADOT  1 627 853   4.63 %
6           Jean LASSALLE  1 101 387   3.13 %
7          Fabien ROUSSEL    802 422   2.28 %
8   Nicolas DUPONT-AIGNAN    725 176   2.06 %
9            Anne HIDALGO    616 478   1.75 %
10        Philippe POUTOU    268 904   0.77 %

## 2. Comparaison des scores départements aux moyennes nationales.
### Question 4

In [44]:
score_departements = df.groupby(['code_departement', 'candidat'])['voix'].sum().reset_index()
score_departements['score'] = (score_departements['voix'] / score_departements.groupby('code_departement')['voix'].transform('sum')) * 100
score_departements["score"] = score_departements["score"]
score_departements.head()

score_departement_11 = score_departements[score_departements['code_departement'] == "11"].sort_values(by='score', ascending=False).reset_index(drop=True)
score_departement_11["score"] = score_departement_11["score"].apply(lambda x: f"{x:.2f} %")

(
    GT(score_departement_11[["code_departement", "candidat", "voix", "score"]])
    .tab_style(style=style.text(font="Times New Roman"), locations=loc.body())
    .tab_style(style=style.text(font="Times New Roman"), locations=loc.column_labels())
)

GT(_tbl_data=   code_departement               candidat   voix    score
0                11          Marine LE PEN  64027  30.14 %
1                11        Emmanuel MACRON  43104  20.29 %
2                11     Jean-Luc MÉLENCHON  42039  19.79 %
3                11           Éric ZEMMOUR  18434   8.68 %
4                11          Jean LASSALLE  12382   5.83 %
5                11       Valérie PÉCRESSE   7350   3.46 %
6                11          Yannick JADOT   6322   2.98 %
7                11           Anne HIDALGO   6166   2.90 %
8                11         Fabien ROUSSEL   5622   2.65 %
9                11  Nicolas DUPONT-AIGNAN   4206   1.98 %
10               11        Philippe POUTOU   1748   0.82 %

### Question 5